# Generated by Django 5.0.6 on 2026-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
