# Generated by Django 5.0.6 on 2026-10-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_bloggerprofile_phone_pinfl_is_ip_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='category',
            field=models.CharField(choices=[('individual', 'Физлицо'), ('self_employed', 'Самозанятый'), ('ip', 'ИП'), ('legal_entity', 'Юрлицо-исполнитель')], default='individual', help_text='Определяет тип реквизитов выплаты: карта (физлицо/самозанятый) или счёт (ИП/юрлицо).', max_length=20, verbose_name='Категория исполнителя'),
        ),
    ]
