# Generated by Django 5.0.6 on 2026-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_bloggerprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='is_legal_entity_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='is_self_employed_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
