# Generated by Django 5.0.6 on 2026-03-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='blogger',
            field=models.ForeignKey(limit_choices_to={'role': 'blogger'}, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='platforms', to='platforms.category'),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('blogger', 'social_type', 'url')},
        ),
    ]
