# Generated by Django 5.0.6 on 2026-10-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_business_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [models.Case(models.When(slug='other', then=1), default=0, output_field=models.IntegerField()), 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
