# Generated by Django 5.0.6 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_category_other_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('suspended', 'Приостановлена'), ('blocked', 'Заблокирована')], default='pending', max_length=20),
        ),
    ]
