# Generated by Django 5.0.6 on 2026-03-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('content_types', models.JSONField(default=list, help_text="List of allowed content types, e.g. ['post', 'stories', 'video', 'review']")),
                ('required_elements', models.JSONField(default=dict, help_text="Required elements in creative, e.g. {'hashtags': ['#brand'], 'mentions': ['@brand']}")),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed'), ('cpa', 'CPA')], default='fixed', max_length=10)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpa_type', models.CharField(blank=True, choices=[('click', 'Click'), ('lead', 'Lead'), ('sale', 'Sale'), ('install', 'Install')], max_length=20, null=True)),
                ('cpa_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpa_tracking_url', models.URLField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Deadline for bloggers to submit content', null=True)),
                ('min_subscribers', models.PositiveIntegerField(default=0)),
                ('min_er', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_socials', models.JSONField(default=list, help_text="List of allowed social platforms, e.g. ['vk', 'telegram']")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('max_bloggers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Response',
                'verbose_name_plural': 'Campaign Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
