# Generated by Django 5.0.6 on 2026-09-12 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_directoffer'),
        ('deals', '0006_conversion_unique_conversion_per_click_and_type'),
        ('platforms', '0003_category_regulated_permitdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directoffer',
            name='unique_direct_offer_per_platform',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='directoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('advertiser', 'campaign', 'platform'), name='unique_active_direct_offer_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'withdrawn'), _negated=True), fields=('blogger', 'campaign', 'platform'), name='unique_active_response_per_platform'),
        ),
    ]
