# Generated by Django 5.0.6 on 2026-10-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_directoffer_unique_direct_offer_per_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEditProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=dict)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Edit Proposal',
                'verbose_name_plural': 'Campaign Edit Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaigneditproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('campaign',), name='one_pending_edit_proposal_per_campaign'),
        ),
    ]
