# Generated by Django 5.0.6 on 2026-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigneditproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, help_text='Что рекламируется: товар, услуга, бренд — заполняет рекламодатель', max_length=255),
        ),
    ]
