# Generated by Django 5.0.6 on 2026-10-06 18:41

from datetime import date
from decimal import Decimal

from django.db import migrations, models

# Список полей и формат значений заморожены на момент миграции (как CampaignForm.Meta.fields
# и campaign_proposals._raw на 06.10.2026), чтобы миграция не зависела от будущих правок формы.
FIELDS = [
    "name", "category", "subject", "description",
    "payment_type", "fixed_price", "budget",
    "cpa_type", "cpa_rate", "cpa_tracking_url",
    "start_date", "end_date", "deadline",
    "min_subscribers", "content_types", "allowed_socials",
    "max_bloggers",
]
LIST_FIELDS = ("content_types", "allowed_socials")
# Значения этих кампаний — и есть одобренная версия: активную кампанию меняют только через модерацию.
APPROVED_STATUSES = ("active", "paused", "completed")


def _raw(value):
    if value is None:
        return ""
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, Decimal):
        return format(value.normalize(), "f") if value == value.to_integral() else str(value)
    return str(value)


def backfill(apps, schema_editor):
    Campaign = apps.get_model("campaigns", "Campaign")
    for campaign in Campaign.objects.filter(status__in=APPROVED_STATUSES, approved_snapshot__isnull=True):
        snapshot = {}
        for name in FIELDS:
            if name in LIST_FIELDS:
                snapshot[name] = [str(v) for v in (getattr(campaign, name) or [])]
            elif name == "category":
                snapshot[name] = str(campaign.category_id or "")
            else:
                snapshot[name] = _raw(getattr(campaign, name))
        campaign.approved_snapshot = snapshot
        campaign.save(update_fields=["approved_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_snapshot',
            field=models.JSONField(blank=True, help_text='Параметры кампании (сырые данные CampaignForm) на момент последнего одобрения — чтобы при повторной модерации показать «было → стало»', null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
