# Generated by Django 5.0.6 on 2026-10-06 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_approved_snapshot'),
        ('platforms', '0004_business_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='response',
            name='unique_active_response_per_platform',
        ),
        migrations.AddField(
            model_name='response',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Комментарий рекламодателя при отклонении — его видит блогер'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['withdrawn', 'rejected']), _negated=True), fields=('blogger', 'campaign', 'platform'), name='unique_active_response_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('blogger', 'campaign'), name='one_pending_response_per_campaign'),
        ),
    ]
