# Generated by Django 5.0.6 on 2026-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_response_rejection_reason_and_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_start',
            field=models.DateField(blank=True, help_text='Приём контента с', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deadline',
            field=models.DateField(blank=True, help_text='Приём контента до (конец окна); не позже чем за 5 рабочих дней до окончания кампании', null=True),
        ),
    ]
