# Generated by Django 5.0.6 on 2026-10-06 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_content_window'),
        ('deals', '0006_conversion_unique_conversion_per_click_and_type'),
        ('platforms', '0004_business_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directoffer',
            name='unique_active_direct_offer_per_platform',
        ),
        migrations.RemoveConstraint(
            model_name='response',
            name='unique_active_response_per_platform',
        ),
        migrations.AlterField(
            model_name='directoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='directoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['rejected', 'expired']), _negated=True), fields=('advertiser', 'campaign', 'platform'), name='unique_active_direct_offer_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['withdrawn', 'rejected', 'expired']), _negated=True), fields=('blogger', 'campaign', 'platform'), name='unique_active_response_per_platform'),
        ),
    ]
