# Generated by Django 5.0.6 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_response_offer_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cpa_type',
            field=models.CharField(blank=True, choices=[('click', 'Клик'), ('lead', 'Заявка'), ('sale', 'Продажа'), ('install', 'Установка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('cpa', 'CPA')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('active', 'Активна'), ('paused', 'На паузе'), ('completed', 'Завершена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaigneditproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ждёт ответа рекламодателя'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='directoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Ждёт ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Ждёт решения'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('withdrawn', 'Отозван'), ('expired', 'Истёк')], default='pending', max_length=20),
        ),
    ]
