# Generated by Django 5.0.6 on 2026-10-08 19:09

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_russian_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoffer',
            name='expires_at',
            field=models.DateTimeField(default=apps.campaigns.models.response_deadline, help_text='Срок ответа — потом EXPIRED'),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда напомнили о сроке ответа', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='expires_at',
            field=models.DateTimeField(default=apps.campaigns.models.response_deadline, help_text='Срок ответа — потом EXPIRED'),
        ),
        migrations.AddField(
            model_name='response',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда напомнили о сроке ответа', null=True),
        ),
    ]
