# Generated by Django 5.0.6 on 2026-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_response_offer_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_early_at',
            field=models.DateTimeField(blank=True, help_text='Когда рекламодатель завершил кампанию досрочно (не по сроку)', null=True),
        ),
        migrations.AlterField(
            model_name='campaigneditproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ждёт ответа рекламодателя'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('closed', 'Закрыто — кампания завершена')], default='pending', max_length=20),
        ),
    ]
