# Generated by Django 5.0.6 on 2026-10-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_finished_early'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoffer',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Дата публикации (ТО 4.3)', null=True),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='reserved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='Когда сумма зарезервирована (ПР 5.2)', null=True),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='response',
            field=models.OneToOneField(blank=True, help_text='Отклик, по которому направлена оферта (пусто — прямое предложение)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='campaigns.response'),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='terms',
            field=models.JSONField(blank=True, default=dict, help_text='Условия кампании на момент направления (ТО 4.10)'),
        ),
    ]
