# Generated by Django 5.0.6 on 2026-10-09 09:54

import django.core.validators
from django.db import migrations, models


def add_snapshot_keys(apps, schema_editor):
    """Одобренная версия кампании получает новые поля со значениями по умолчанию — повторная модерация не покажет
    их как непроверенную правку."""
    Campaign = apps.get_model("campaigns", "Campaign")
    for campaign in Campaign.objects.exclude(approved_snapshot=None):
        snapshot = dict(campaign.approved_snapshot or {})
        if not snapshot or "approval_required" in snapshot:
            continue
        snapshot.update(approval_required="True", content_lead_days="5", review_days="2")
        Campaign.objects.filter(pk=campaign.pk).update(approved_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_offer_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approval_required',
            field=models.BooleanField(default=True, help_text='Без согласования рекламодателя публиковать нельзя', verbose_name='Согласовать материал перед публикацией'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_lead_days',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Сдать материал за, рабочих дней до даты публикации'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='review_days',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Срок рассмотрения материала, рабочих дней'),
        ),
        migrations.RunPython(add_snapshot_keys, migrations.RunPython.noop),
    ]
