# Generated by Django 5.0.6 on 2026-10-09 10:38

import django.core.validators
from django.db import migrations, models

DEFAULTS = {"content_units": "1", "min_retention_days": "3", "rights_owner": "blogger", "reuse_allowed": "False",
            "evidence_required": []}


def add_snapshot_keys(apps, schema_editor):
    """Одобренная версия получает новые поля со значениями по умолчанию — повторная модерация не покажет их
    как непроверенную правку. Пустые текстовые поля и так совпадают."""
    Campaign = apps.get_model("campaigns", "Campaign")
    for campaign in Campaign.objects.exclude(approved_snapshot=None):
        snapshot = dict(campaign.approved_snapshot or {})
        if not snapshot or "content_units" in snapshot:
            continue
        snapshot.update(DEFAULTS)
        Campaign.objects.filter(pk=campaign.pk).update(approved_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_content_approval_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='acceptance_criteria',
            field=models.TextField(blank=True, verbose_name='Критерии приёмки'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_restrictions',
            field=models.TextField(blank=True, verbose_name='Ограничения по тематике и содержанию'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_units',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество единиц контента'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='disclosures',
            field=models.TextField(blank=True, verbose_name='Обязательные предупреждения и раскрытия'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='evidence_required',
            field=models.JSONField(blank=True, default=list, help_text='Что исполнитель прикладывает к ссылке на публикацию: screenshot, statistics, publication_time, retention', verbose_name='Доказательства исполнения'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='forbidden_phrases',
            field=models.TextField(blank=True, verbose_name='Запрещённые формулировки'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='key_message',
            field=models.TextField(blank=True, verbose_name='Основное сообщение'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mandatory_points',
            field=models.TextField(blank=True, verbose_name='Обязательные тезисы'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_retention_days',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Минимальный срок сохранения публикации, дней'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reuse_allowed',
            field=models.BooleanField(default=False, verbose_name='Право на репост, таргет, адаптацию'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rights_owner',
            field=models.CharField(choices=[('blogger', 'Исполнителю'), ('advertiser', 'Рекламодателю (после оплаты)')], default='blogger', max_length=20, verbose_name='Исключительные права на контент'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags_requirements',
            field=models.TextField(blank=True, verbose_name='Хештеги, ссылки, отметки'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='visual_requirements',
            field=models.TextField(blank=True, verbose_name='Требования к визуалу и монтажу'),
        ),
        migrations.RunPython(add_snapshot_keys, migrations.RunPython.noop),
    ]
