# Generated by Django 5.0.6 on 2026-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_card_and_offer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoffer',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ставка комиссии платформы, зафиксированная при направлении; пусто — оферта до тарифных уровней', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='reserved_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
