# Generated by Django 5.0.6 on 2026-10-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_snapshot_key(apps, schema_editor):
    """Одобренные кампании — открытые: ключ в снимке, чтобы повторная модерация не показала его правкой."""
    Campaign = apps.get_model("campaigns", "Campaign")
    for campaign in Campaign.objects.exclude(approved_snapshot=None):
        snapshot = dict(campaign.approved_snapshot or {})
        if snapshot and "visibility" not in snapshot:
            snapshot["visibility"] = "open"
            Campaign.objects.filter(pk=campaign.pk).update(approved_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_offer_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='visibility',
            field=models.CharField(choices=[('open', 'Открытая — в общем списке, отклик любого подходящего исполнителя'), ('closed', 'Закрытая — только для приглашённых исполнителей')], default='open', max_length=10, verbose_name='Тип кампании'),
        ),
        migrations.CreateModel(
            name='CampaignInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_invitations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaigninvitation',
            constraint=models.UniqueConstraint(fields=('campaign', 'blogger'), name='one_invitation_per_blogger'),
        ),
        migrations.RunPython(add_snapshot_key, migrations.RunPython.noop),
    ]
