# Generated by Django 5.0.6 on 2026-03-29 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('reserve', 'Reserve'), ('release', 'Release'), ('payment', 'Payment'), ('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('correction', 'Correction'), ('test_credit', 'Test Credit (Demo)')], max_length=20),
        ),
        migrations.CreateModel(
            name='TestBalanceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_test_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'is_demo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='test_balance_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Balance Grant',
                'verbose_name_plural': 'Test Balance Grants',
                'ordering': ['-granted_at'],
            },
        ),
    ]
