# Generated by Django 5.0.6 on 2026-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_test_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('reserve', 'Reserve'), ('release', 'Release'), ('payment', 'Payment'), ('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('correction', 'Correction'), ('test_credit', 'Test Credit (Demo)'), ('payout', 'Payout')], max_length=20),
        ),
    ]
