# Generated by Django 5.0.6 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_transaction_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('reserve', 'Резерв'), ('release', 'Возврат резерва'), ('payment', 'Оплата сделки'), ('earning', 'Заработок'), ('withdrawal', 'Вывод'), ('refund', 'Возврат вывода'), ('correction', 'Корректировка'), ('test_credit', 'Test Credit (Demo)'), ('payout', 'Выплата')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Выплачена')], default='pending', max_length=20),
        ),
    ]
