# Generated by Django 5.0.6 on 2026-10-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_russian_choice_labels'),
        ('campaigns', '0014_offer_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Оферта, под которую зарезервировано или с которой возвращено', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.directoffer'),
        ),
    ]
