# Generated by Django 5.0.6 on 2026-10-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_offer_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite_type', models.CharField(choices=[('card', 'Карта'), ('account', 'Расчётный счёт')], max_length=20)),
                ('card_number', models.CharField(blank=True, help_text='16 цифр, без пробелов', max_length=16)),
                ('card_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('bank_mfo', models.CharField(blank=True, max_length=10, verbose_name='МФО банка')),
                ('bank_inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН банка')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payout_requisites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'blogger'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requisites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реквизиты выплаты',
                'verbose_name_plural': 'Реквизиты выплаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payoutrequisites',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_payout_requisites_per_user'),
        ),
    ]
