# Generated by Django 5.0.6 on 2026-10-09 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payoutrequisites_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_until', models.DateField(blank=True, help_text='Пусто — бессрочно', null=True)),
                ('note', models.CharField(blank=True, help_text='Основание: договор, скидка и т. п.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_tariff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Special tariff',
                'verbose_name_plural': 'Special tariffs',
            },
        ),
    ]
