# Generated by Django 5.0.6 on 2026-03-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo account — test balance only, withdrawals blocked'),
        ),
    ]
