# Generated by Django 5.0.6 on 2026-09-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Автоматически')], default='manual', max_length=10, verbose_name='Источник')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Пусто — блокировка бессрочная.', null=True, verbose_name='Заблокирован до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Заблокированный IP',
                'verbose_name_plural': 'Заблокированные IP',
                'ordering': ['-created_at'],
            },
        ),
    ]
