# Generated by Django 5.0.6 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blockedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('advertiser', 'Рекламодатель'), ('blogger', 'Блогер')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активен'), ('blocked', 'Заблокирован'), ('deleted', 'Удалён')], default='pending', max_length=20),
        ),
    ]
