# Generated by Django 5.0.6 on 2026-10-06 18:52

import apps.registration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_legalentityapplication_user_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentityapplication',
            name='inn',
            field=models.CharField(max_length=20, validators=[apps.registration.validators.validate_inn], verbose_name='ИНН'),
        ),
    ]
