# Generated by Django 5.0.6 on 2026-10-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_legal_entity_inn_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipapplication',
            name='target_category',
            field=models.CharField(choices=[('ip', 'ИП'), ('self_employed', 'Самозанятый'), ('legal_entity', 'Юрлицо-исполнитель')], default='ip', help_text='Какую категорию исполнителя подтверждает заявка', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='document_number',
            field=models.CharField(blank=True, help_text='Номер документа; для юрлица — ИНН', max_length=100),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='document_type',
            field=models.CharField(choices=[('patent', 'Патент'), ('spravka', 'Справка'), ('self_employed_cert', 'Справка о регистрации самозанятого'), ('legal_entity_extract', 'Свидетельство/выписка юрлица')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='identity_verification',
            field=models.ForeignKey(blank=True, help_text='Должна быть VERIFIED перед подачей заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_applications', to='registration.identityverification'),
        ),
    ]
