# Generated by Django 5.0.6 on 2026-03-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_initial'),
        ('deals', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_deal_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='advertiser',
            field=models.ForeignKey(limit_choices_to={'role': 'advertiser'}, on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_advertiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='blogger',
            field=models.ForeignKey(limit_choices_to={'role': 'blogger'}, on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_blogger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='deal',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='platforms.platform'),
        ),
        migrations.AddField(
            model_name='deal',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='campaigns.response'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealstatuslog',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='deals.deal'),
        ),
    ]
