# Generated by Django 5.0.6 on 2026-03-28 15:22

import apps.deals.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Click Log',
                'verbose_name_plural': 'Click Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=apps.deals.models._generate_slug, max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Tracking Link',
                'verbose_name_plural': 'Tracking Links',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('click', 'Click'), ('lead', 'Lead'), ('sale', 'Sale'), ('install', 'Install')], default='click', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credited', models.BooleanField(default=False)),
                ('postback_raw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='deals.clicklog')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='deals.trackinglink')),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clicklog',
            name='tracking_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='deals.trackinglink'),
        ),
    ]
