# Generated by Django 5.0.6 on 2026-09-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_retention_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.UniqueConstraint(fields=('click_log', 'conversion_type'), name='unique_conversion_per_click_and_type'),
        ),
    ]
