# Generated by Django 5.0.6 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_conversion_unique_conversion_per_click_and_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(choices=[('click', 'Клик'), ('lead', 'Заявка'), ('sale', 'Продажа'), ('install', 'Установка')], default='click', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('waiting_payment', 'Ожидает оплаты'), ('in_progress', 'В работе'), ('on_approval', 'На согласовании'), ('waiting_publication', 'Ждёт публикации'), ('published', 'Опубликована'), ('checking', 'На проверке'), ('completed', 'Завершена'), ('disputed', 'Оспорена'), ('cancelled', 'Отменена')], default='waiting_payment', max_length=30),
        ),
    ]
