# Generated by Django 5.0.6 on 2026-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_russian_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Дата публикации из оферты (ТО 4.3)', null=True),
        ),
    ]
