# Generated by Django 5.0.6 on 2026-10-09 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_offer_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, help_text='Когда уведомили стороны о просрочке даты публикации (сбрасывается при переносе)', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='publication_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда напомнили исполнителю о дате публикации (сбрасывается при переносе)', null=True),
        ),
        migrations.CreateModel(
            name='PublicationDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ждёт ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('closed', 'Закрыто')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='deals.deal')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_date_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicationdatechange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('deal',), name='one_pending_date_change_per_deal'),
        ),
    ]
