# Generated by Django 5.0.6 on 2026-10-09 09:55

from django.db import migrations, models


def count_past_submissions(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    Deal.objects.filter(creative_submitted_at__isnull=False).update(creative_submissions=1)


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_publication_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='content_lead_days',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='creative_submissions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сколько раз материал отправлен на согласование'),
        ),
        migrations.AddField(
            model_name='deal',
            name='review_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='deal',
            name='review_overdue_notified_at',
            field=models.DateTimeField(blank=True, help_text='Когда уведомили стороны, что срок рассмотрения материала истёк', null=True),
        ),
        migrations.RunPython(count_past_submissions, migrations.RunPython.noop),
    ]
