# Generated by Django 5.0.6 on 2026-10-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_content_approval_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='evidence_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='min_retention_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='publication_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Рекламодатель принял публикацию (без оплаты — оплата по сроку)', null=True),
        ),
        migrations.CreateModel(
            name='DealEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='deal_evidence/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='deals.deal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
