# Generated by Django 5.0.6 on 2026-10-09 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_retention_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сколько фактически перечислено исполнителю (раздел суммы, компенсация); пусто — вся сумма или ничего', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('placement', 'Размещение не соответствует условиям оферты'), ('retention', 'Публикация удалена или скрыта раньше срока сохранения'), ('deadline', 'Нарушен срок'), ('unapproved', 'Размещён несогласованный материал'), ('no_review', 'Рекламодатель не рассматривает материал после правок'), ('not_accepted', 'Исполнение не принимается без оснований'), ('other', 'Другое')], max_length=30)),
                ('violated_term', models.CharField(help_text='Какое условие оферты или правило нарушено', max_length=255)),
                ('description', models.TextField()),
                ('demand', models.CharField(choices=[('refund', 'Вернуть деньги рекламодателю'), ('partial_refund', 'Частичный возврат'), ('refuse_payout', 'Отказать в выплате'), ('revision', 'Дополнительная доработка'), ('payout', 'Перечислить оплату исполнителю'), ('compensation', 'Компенсация за выполненную работу'), ('other', 'Иное')], max_length=30)),
                ('demand_details', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='Ссылки на доказательства, по одной в строке')),
                ('status', models.CharField(choices=[('open', 'Рассматривается'), ('extra_docs', 'Дополнительное документирование'), ('resolved', 'Решение принято')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_until', models.DateTimeField()),
                ('decide_until', models.DateTimeField()),
                ('explanation', models.TextField(blank=True)),
                ('explained_at', models.DateTimeField(blank=True, null=True)),
                ('extra_docs_until', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('to_blogger', 'Перечислить исполнителю в полном объёме'), ('to_advertiser', 'Вернуть рекламодателю в полном объёме'), ('split', 'Распределить между сторонами'), ('compensation', 'Компенсация исполнителю за выполненную работу')], max_length=20)),
                ('blogger_part', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='deals.deal')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='claim_files/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='deals.claim')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'extra_docs'])), fields=('deal',), name='one_open_claim_per_deal'),
        ),
    ]
