# Generated by Django 5.0.6 on 2026-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_termination_by_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия сверх вознаграждения по тарифу на момент оферты; пусто — прежняя модель (из суммы блогера)', max_digits=5, null=True),
        ),
    ]
