# Generated by Django 5.0.6 on 2026-09-12 20:35

import apps.business_queries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='Вводный абзац на странице')),
                ('source_task_path', models.CharField(blank=True, help_text='Например: task/registration 12092026 — к какой задаче относится', max_length=255)),
                ('token', models.SlugField(default=apps.business_queries.models._generate_token, max_length=32, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Опросник для бизнеса',
                'verbose_name_plural': 'Опросники для бизнеса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('choice', 'Выбор A/B'), ('note', 'Свободный текст')], default='choice', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('context_text', models.TextField(blank=True, help_text='Поясняющий абзац (почему спрашиваем)')),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='business_queries.businessquery')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('answers', models.JSONField(default=dict, help_text="{question_id: 'A'|'B'|'текст для note'}")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='business_queries.businessquery')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Что нужно сделать — свободный текст')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('waiting_business', 'Ждём бизнес'), ('done', 'Закрыт')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businessquery',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='business_queries.ticket'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Скриншот или PDF', upload_to=apps.business_queries.models.ticket_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='business_queries.ticket')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='business_queries.ticket')),
            ],
            options={
                'verbose_name': 'Смена статуса тикета',
                'verbose_name_plural': 'Смены статуса тикета',
                'ordering': ['created_at'],
            },
        ),
    ]
