# Generated by Django 5.0.6 on 2026-03-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict, help_text="Notification preferences, e.g. {'email': True, 'push': False, 'deal_created': True, ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_completed', 'Deal Completed'), ('deal_cancelled', 'Deal Cancelled'), ('deal_disputed', 'Deal Disputed'), ('creative_submitted', 'Creative Submitted'), ('creative_approved', 'Creative Approved'), ('creative_rejected', 'Creative Rejected'), ('payment_received', 'Payment Received'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('campaign_response', 'Campaign Response'), ('campaign_status', 'Campaign Status Changed'), ('platform_moderated', 'Platform Moderated'), ('system', 'System')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
