# Generated by Django 5.0.6 on 2026-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_completed', 'Deal Completed'), ('deal_cancelled', 'Deal Cancelled'), ('deal_disputed', 'Deal Disputed'), ('creative_submitted', 'Creative Submitted'), ('creative_approved', 'Creative Approved'), ('creative_rejected', 'Creative Rejected'), ('payment_received', 'Payment Received'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('campaign_response', 'Campaign Response'), ('campaign_status', 'Campaign Status Changed'), ('campaign_changes_proposed', 'Campaign Changes Proposed'), ('campaign_changes_accepted', 'Campaign Changes Accepted'), ('campaign_changes_declined', 'Campaign Changes Declined'), ('campaign_moderation_requested', 'Campaign Moderation Requested'), ('publication_submitted', 'Publication Submitted'), ('platform_moderated', 'Platform Moderated'), ('response_accepted', 'Response Accepted'), ('response_rejected', 'Response Rejected'), ('direct_offer_received', 'Direct Offer Received'), ('direct_offer_accepted', 'Direct Offer Accepted'), ('direct_offer_rejected', 'Direct Offer Rejected'), ('legal_entity_assigned', 'Legal Entity Assigned'), ('legal_entity_approved', 'Legal Entity Approved'), ('legal_entity_rejected', 'Legal Entity Rejected'), ('ip_application_approved', 'IP Application Approved'), ('ip_application_rejected', 'IP Application Rejected'), ('system', 'System')], max_length=40),
        ),
    ]
