# Generated by Django 5.0.6 on 2026-10-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_response_offer_expired'),
        ('notifications', '0006_notification_type_publication_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_campaign',
            field=models.ForeignKey(blank=True, help_text='Кампания, страница которой тоже гасит уведомление', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='campaigns.campaign'),
        ),
    ]
